2024-02-12 00:19:29,254 INFO    MainThread:2305894 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-12 00:19:29,254 INFO    MainThread:2305894 [wandb_setup.py:_flush():76] Configure stats pid to 2305894
2024-02-12 00:19:29,254 INFO    MainThread:2305894 [wandb_setup.py:_flush():76] Loading settings from /u3/oqcardos/.config/wandb/settings
2024-02-12 00:19:29,254 INFO    MainThread:2305894 [wandb_setup.py:_flush():76] Loading settings from /u3/oqcardos/motion_prediction/per-motion-prediction/wandb/settings
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_init.py:_log_setup():526] Logging user logs to /u3/oqcardos/motion_prediction/per-motion-prediction/wandb/run-20240212_001929-gh3enjwl/logs/debug.log
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_init.py:_log_setup():527] Logging internal logs to /u3/oqcardos/motion_prediction/per-motion-prediction/wandb/run-20240212_001929-gh3enjwl/logs/debug-internal.log
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_init.py:init():566] calling init triggers
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'optimizer': 'AdamW', 'lr': 5e-05, 'usingScheduler': 'linear', 'architecture': 'Bert', 'dataset': 'single-supports', 'epochs': 100}
2024-02-12 00:19:29,255 INFO    MainThread:2305894 [wandb_init.py:init():591] re-initializing run, found existing run on stack: owv9jzp2
2024-02-12 00:19:29,257 INFO    MainThread:2305894 [wandb_run.py:_finish():1970] finishing run oqcardoso/LLM_TOTURIAL/owv9jzp2
2024-02-12 00:19:29,260 ERROR   MainThread:2305894 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-02-12 00:19:29,260 INFO    MainThread:2305894 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-12 00:19:29,260 INFO    MainThread:2305894 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-12 00:19:29,261 INFO    MainThread:2305894 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-12 00:19:29,261 INFO    MainThread:2305894 [wandb_run.py:_restore():2193] restore
2024-02-12 00:19:29,261 INFO    MainThread:2305894 [wandb_run.py:_restore():2199] restore done
2024-02-12 00:19:58,859 INFO    MainThread:2305894 [wandb_init.py:init():616] starting backend
2024-02-12 00:19:58,860 INFO    MainThread:2305894 [wandb_init.py:init():620] setting up manager
2024-02-12 00:19:58,863 INFO    MainThread:2305894 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-12 00:19:58,864 INFO    MainThread:2305894 [wandb_init.py:init():628] backend started and connected
2024-02-12 00:19:58,885 INFO    MainThread:2305894 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-12 00:19:58,885 INFO    MainThread:2305894 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-12 00:19:58,885 INFO    MainThread:2305894 [wandb_init.py:init():720] updated telemetry
2024-02-12 00:19:58,901 INFO    MainThread:2305894 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
